### ISSUE TITLE
Issue with refreshing props on sites/database/site

### ISSUE THREAD

**Issue by jtmeneses707** [beam-ntth/uc-ctct#12]
When using the add or remove button, changes are not properly reflected, even when adding a longer timeout. Manually refreshing page results in the right changes.

**Comment by jtmeneses707** [comment]
Issue is with the filteredData.map. When replacing with just data.map, the page correctly refreshes.

**Comment by beam-ntth** [comment]
@jtmeneses707 Please do not change from `filteredData` to `data`, as `filteredData` is very important when the user wants to use the search bar. I'll investigate the problem with add/remove sites not being refreshed properly.

**Comment by beam-ntth** [comment]
Problem resolved by using `useEffect()` to reinitialized data coming from DB
```javascript
// Reinitialized displayed data when there are any changes to the DB data
  useEffect(() => {
    setFilteredData(data)
  }, [data])
```
