### ISSUE TITLE
Error message when clicking on delete for a region with 0 sites

### ISSUE THREAD

**Issue by m-tilve** [beam-ntth/uc-ctct#7]
In the regions page, when you click on the delete icon for a region with 1 site there is an error message pop up and it updates the number of sites to one less ( from 1 site to 0 sites), but the row for the region is still there. After clicking delete again, the row disappears which is something that we don't want to happen.
For regions with 0 sites, if we click the row disappears but maybe we should print something like  a message pop up saying " Nothing to delete" or " There are currently no sites", but keep the region there

**Comment by jtmeneses707** [comment]
Solution: Checking if the error code is a 404 -> This means the resource was probably already deleted. We can then continue. Will work on this solution sometime soon.

**Comment by beam-ntth** [comment]
@m-tilve  I do not believe there is an issue here. If anything, it makes sense to delete a region with no sites because why would you keep an empty record on the DB?
@jtmeneses707 Correct me if I'm wrong, but the issue raised by Maria was not a concurrency issue.

**Comment by beam-ntth** [comment]
@m-tilve Thanks for the update. 
- Okay, it seems like your first encounter was definitely a concurrency issue. We will take care of that in the next update.
- As for a pop-up, we will implement a waring for the users in the next update as well.

**Comment by beam-ntth** [comment]
Added TODO to README
