### ISSUE TITLE
Issue with setOpenEdit() on sites/database/site? page.

### ISSUE THREAD

**Issue by jtmeneses707** [beam-ntth/uc-ctct#8]
ReferenceError: setOpenEditForm is not defined

**Comment by beam-ntth** [comment]
Could you copy the full error with the line number?

**Comment by jtmeneses707** [comment]
pages/sites/database/site.js (87:37) @ onClick
  85 |   }
  86 |   }
> 87 |   onClick={() => setOpenEditForm(x.id)} />
     |                 ^
  88 | <FaRegTrashAlt color={trashHover[ind] ? "#CD0000" : "#C4C4C4"} size={trashHover[ind] ? 38 : 35}
  89 |   style={{ cursor: 'pointer', transition: '0.2s linear', marginLeft: '1rem' }}
  90 |   onMouseEnter={() => {

**Comment by beam-ntth** [comment]
Solved
