### ISSUE TITLE
Add New Clinic button does not work

### ISSUE THREAD

**Issue by jtmeneses707** [beam-ntth/uc-ctct#9]

**Comment by beam-ntth** [comment]
Could you elaborate on this issue? 

Do you mean:
1. There was no pop-up for you to create a clinic?
2. There was an error when you clicked 'create clinic'?
3. Nothing showed up after you clicked 'create clinic' and the page was reloaded?

**Comment by jtmeneses707** [comment]
No pop up occurs - pressing the + button does not result in an overlay.
